export const paletterPrimary: string;
export const paletteSecondary: string;
export const paletteAccent: string;
export const primaryTintQuarter: string;
export const secondaryTintQuarter: string;
export const palettePale: string;
export const paletteDark: string;
export const darkTintHalf: string;
export const paletteShine: string;
